name: polarfire
version: 22-1
summary: Microchip PolarFire SoC Icicle gadget
description: |
  Support files for booting the Microchip PolarFire SoC Icicle
type: gadget
base: core22
assumes: [kernel-assets]
adopt-info: u-boot

architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

confinement: strict

parts:
  boot-scr:
    plugin: nil
    source: boot-scr/
    override-build: |
      mkimage \
        -C none \
        -O linux \
        -T script \
        -d boot.scr.in \
        -n 'U-Boot boot script' \
        ${CRAFT_PART_INSTALL}/boot.scr
    build-packages:
      - u-boot-tools

  # Make an empty environment file so that Ubuntu Core can adjust the boot
  # variables later
  boot-sel:
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkenvimage -r -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

  # Required by Ubuntu Core
  uboot-conf:
    plugin: nil
    override-build: |
      touch ${CRAFT_PART_INSTALL}/uboot.conf

  u-boot:
    plugin: nil
    stage-packages:
      - u-boot-microchip:${CRAFT_TARGET_ARCH}
    override-build: |
      craftctl default

      UBOOT_VERSION="$(strings ${CRAFT_PART_INSTALL}/usr/lib/u-boot/microchip_mpfs_icicle/u-boot.bin | grep '^U-Boot ' | cut -f 2 -d\ )"
      craftctl set version="${UBOOT_VERSION}"
      craftctl set grade="stable"
    organize:
      usr/lib/u-boot/microchip_icicle/u-boot.payload: payload.bin
    stage:
      - payload.bin

  # Provides uuidgen for use in prepare-device hooks
  prepare-device:
    plugin: nil
    stage-packages:
      - uuid-runtime

slots:
  icicle-gpio-0:
    interface: gpio
    number: 0
  icicle-gpio-1:
    interface: gpio
    number: 1
  icicle-gpio-2:
    interface: gpio
    number: 2
  icicle-gpio-3:
    interface: gpio
    number: 3
  icicle-gpio-4:
    interface: gpio
    number: 4
  icicle-gpio-5:
    interface: gpio
    number: 5
  icicle-gpio-6:
    interface: gpio
    number: 6
  icicle-gpio-7:
    interface: gpio
    number: 7
  icicle-gpio-8:
    interface: gpio
    number: 8
  icicle-gpio-9:
    interface: gpio
    number: 9
  icicle-gpio-10:
    interface: gpio
    number: 10
  icicle-gpio-11:
    interface: gpio
    number: 11
  icicle-gpio-12:
    interface: gpio
    number: 12
  icicle-gpio-13:
    interface: gpio
    number: 13
  icicle-gpio-14:
    interface: gpio
    number: 14
  icicle-gpio-15:
    interface: gpio
    number: 15
  icicle-gpio-16:
    interface: gpio
    number: 16
  icicle-gpio-17:
    interface: gpio
    number: 17
  icicle-gpio-18:
    interface: gpio
    number: 18
  icicle-gpio-19:
    interface: gpio
    number: 19
  icicle-gpio-20:
    interface: gpio
    number: 20
  icicle-gpio-21:
    interface: gpio
    number: 21
  icicle-gpio-22:
    interface: gpio
    number: 22
  icicle-gpio-23:
    interface: gpio
    number: 23
  icicle-gpio-24:
    interface: gpio
    number: 24
  icicle-gpio-25:
    interface: gpio
    number: 25
  icicle-gpio-26:
    interface: gpio
    number: 26
  icicle-gpio-27:
    interface: gpio
    number: 27
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
  serial0:
    interface: serial-port
    path: /dev/ttyS0
  serial1:
    interface: serial-port
    path: /dev/ttyS1
  serial2:
    interface: serial-port
    path: /dev/ttyS2
  serial3:
    interface: serial-port
    path: /dev/ttyS3
  pwm0:
    interface: pwm
    chip-number: 0
    channel: 0
  pwm1:
    interface: pwm
    chip-number: 0
    channel: 1
  pwm2:
    interface: pwm
    chip-number: 0
    channel: 2
  pwm3:
    interface: pwm
    chip-number: 0
    channel: 3
  pwm4:
    interface: pwm
    chip-number: 0
    channel: 4
  pwm5:
    interface: pwm
    chip-number: 0
    channel: 5
  pwm6:
    interface: pwm
    chip-number: 0
    channel: 6
  pwm7:
    interface: pwm
    chip-number: 0
    channel: 7
  pwm8:
    interface: pwm
    chip-number: 0
    channel: 8
  pwm9:
    interface: pwm
    chip-number: 0
    channel: 9
  pwm10:
    interface: pwm
    chip-number: 0
    channel: 10
  pwm11:
    interface: pwm
    chip-number: 0
    channel: 11
  pwm12:
    interface: pwm
    chip-number: 0
    channel: 12
  pwm13:
    interface: pwm
    chip-number: 0
    channel: 13
  pwm14:
    interface: pwm
    chip-number: 0
    channel: 14
  pwm15:
    interface: pwm
    chip-number: 0
    channel: 15
