name: virt
version: 22-1
summary: RISCV virt board gadget
description: |
  Support files for booting Qemu's RISCV virt board.
type: gadget
base: core22
assumes: [kernel-assets]
architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

confinement: strict
grade: stable

parts:
  boot-scr:
    plugin: nil
    source: sources/
    build-packages:
      - sed
      - u-boot-tools
    override-build: |
      mkimage \
        -T script \
        -A riscv \
        -C none \
        -n 'Boot Script' \
        -d ${CRAFT_PROJECT_DIR}/sources/boot.scr.in \
        ${CRAFT_PART_INSTALL}/boot.scr

  u-boot-smode:
    plugin: make
    source: https://github.com/u-boot/u-boot
    source-type: git
    source-branch: v2022.07
    source-depth: 1
    build-packages:
      - bc
      - bison
      - build-essential
      - flex
      - libpython3-dev
      - libssl-dev
      - on amd64:
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
    override-build: |
      ARCH=riscv make qemu-riscv64_smode_defconfig

      # Relevant config options for Qemu
      echo 'CONFIG_ENV_IS_IN_FAT=y'               >> .config
      echo 'CONFIG_ENV_FAT_FILE="boot.scr"'       >> .config
      echo 'CONFIG_ENV_FAT_INTERFACE="virtio"'    >> .config
      echo '# CONFIG_ENV_IS_NOWHERE is not set'   >> .config
      echo 'CONFIG_ENV_FAT_DEVICE_AND_PART="0:1"' >> .config

      echo "yes" "" | ARCH=riscv make oldconfig

      ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- make

      cp -f ${CRAFT_PART_BUILD}/u-boot.bin ${CRAFT_PART_INSTALL}/

      tools/mkenvimage \
        -r -s 4096 \
        -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

      touch ${CRAFT_PART_INSTALL}/uboot.conf
    prime:
      - -u-boot.bin

  opensbi:
    after: [u-boot-smode]
    plugin: make
    source: https://github.com/riscv-software-src/opensbi
    source-type: git
    source-commit: 7f09fba86e439808e0b40bdf536937c42e1ea2c9
    source-depth: 1
    build-packages:
      - build-essential
      - on amd64:
        - gcc-riscv64-linux-gnu
      - else:
        - gcc
    override-build: |
      ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- make PLATFORM=generic FW_PAYLOAD_PATH=${CRAFT_STAGE}/u-boot.bin

      cp -f build/platform/generic/firmware/fw_payload.bin ${CRAFT_PART_INSTALL}/
