#!/bin/sh

set -eu

exec >> $SNAP_COMMON/prepare-device-hook.log 2>&1

if [ -z "$MODEL_APIKEY" ] ; then
    exit 0
fi

snapctl set registration.proposed-serial="\"$(date -u)\""
snapctl set device-service.url="https://serial-vault-partners.canonical.com/v1/"
snapctl set device-service.headers="{\"api-key\": \"$MODEL_APIKEY\"}"
