---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Isaac True

name: odroid-hc4-gadget
base: core22
summary: Gadget snap for the ODROID HC4 platform
description: |
  Gadget snap for the ODROID HC4 platform
type: gadget
confinement: strict
grade: stable
version: v2015.01

architectures:
  - build-on: amd64
    build-for: [arm64]

parts:
  # The Hardkernel U-Boot only supports <= GCC 4, which isn't available in 20.04
  toolchain-aarch64:
    source: https://releases.linaro.org/archive/14.11/components/toolchain/binaries/aarch64-none-elf/gcc-linaro-4.9-2014.11-x86_64_aarch64-elf.tar.xz
    plugin: dump
    organize:
      "*": toolchain-aarch64/
    prime:
      - -*

  # Not sure why armhf is needed but it's in the install guide for the ODROID HC4 (maybe for the ATF?)
  toolchain-armhf:
    source: https://releases.linaro.org/archive/14.11/components/toolchain/binaries/arm-none-eabi/gcc-linaro-4.9-2014.11-x86_64_arm-eabi.tar.xz
    plugin: dump
    organize:
      "*": toolchain-armhf/
    prime:
      - -*

  # From https://wiki.odroid.com/odroid-hc4/software/building_u-boot
  u-boot:
    after:
      - toolchain-armhf
      - toolchain-aarch64
    plugin: nil
    build-environment:
      - PATH: "${CRAFT_STAGE}/toolchain-aarch64/bin:${CRAFT_STAGE}/toolchain-armhf/bin:/usr/lib/ccache/:${PATH}"
    source: https://github.com/hardkernel/u-boot.git
    source-type: git
    source-branch: odroidg12-v2015.01
    override-build: |
      make odroidc4_defconfig
      make -j$(nproc)
      cp sd_fuse/u-boot.bin ${CRAFT_PART_INSTALL}/
    build-packages:
      - bc
      - make

  # U-Boot script
  boot-scr:
    after:
      - u-boot
    plugin: nil
    source: u-boot
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage -A arm64 -T script -C none -n 'Boot Script' -d boot.scr \
        ${CRAFT_PART_INSTALL}/boot.scr

  # Make an empty environment file so that Ubuntu Core can edit it later
  boot-sel:
    after:
      - u-boot
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkenvimage -r -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

  # Required by Ubuntu Core
  uboot-conf:
    plugin: nil
    override-build: |
      touch ${CRAFT_PART_INSTALL}/uboot.conf

  hooks:
    plugin: nil
    source: hooks
    stage-packages:
      - uuid-runtime:${CRAFT_TARGET_ARCH}
    override-build: |
      if [[ -z ${MODEL_APIURL+x} || -z ${MODEL_APIKEY+x} ]]; then
        echo "MODEL_APIKEY or MODEL_APIURL not set; not creating prepare-device hook"
      else
        sed -i "s;<<<MODEL_APIURL>>>;${MODEL_APIURL};" \
          ${CRAFT_PART_BUILD}/prepare-device.inc
        sed -i "s;<<<MODEL_APIKEY>>>;${MODEL_APIKEY};" \
          ${CRAFT_PART_BUILD}/prepare-device.inc

        install -Dm0755 ${CRAFT_PART_BUILD}/prepare-device.inc \
          ${CRAFT_PART_INSTALL}/snap/hooks/prepare-device
      fi
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/bash-completion
