name: nezha
version: 22-1
summary: Nezha board gadget
description: |
  Support files for booting the Nezha board
base: core22
type: gadget

confinement: strict
grade: stable

assumes: [kernel-assets]

architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]

parts:
  boot-scr:
    plugin: nil
    source: u-boot/
    build-packages:
      - u-boot-tools
    override-build: |
      mkimage \
        -T script \
        -C none \
        -n 'Boot Script' \
        -d boot.scr.in \
        ${CRAFT_PART_INSTALL}/boot.scr

  boot0:
    plugin: nil
    stage-packages:
      - nezha-boot0
    organize:
      usr/lib/u-boot/nezha/boot0_sdcard_sun20iw1p1.bin: boot0_sdcard_sun20iw1p1.bin
    stage:
      - boot0_sdcard_sun20iw1p1.bin

  u-boot:
    plugin: nil
    stage-packages:
      - u-boot-nezha
    organize:
      usr/lib/u-boot/nezha/u-boot.toc1: u-boot.toc1
    stage:
      - u-boot.toc1

  boot-sel:
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkenvimage -r -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

      touch ${CRAFT_PART_INSTALL}/uboot.conf
