name: visionfive2
adopt-info: grub
type: gadget
base: core24
summary: An Ubuntu Core gadget for the StarFive VisionFive 2
description: |
  This snap provides the u-boot and GRUB binaries for booting the RISC-V
  StarFive VisionFive 2.

  Additionally it includes the gadget.yaml which defines our partition layout
  and any default configuration options for our Ubuntu Core device.

  ** Note that the license information of this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  The uEnv.txt, gadget.yaml, grub.builtin, and snapcraft.yaml are licensed under CC-BY-SA-4.0

  You can find many licenses for the contents of this snap at the following locations:

  All provided: licenses/

grade: devel
confinement: strict

license: "Beerware AND BSD-2-Clause AND BSD-3-Clause AND CC-BY-SA-3.0 AND CC-BY-SA-4.0 AND GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-2.1 AND MIT"
website: https://github.com/canonical/iot-field-gadget-snap
issues: https://github.com/canonical/iot-field-gadget-snap/issues

assumes: [kernel-assets]

platforms:
  riscv64:
    build-on:  [amd64, riscv64]
    build-for: [riscv64]

# Provides GRUB and u-boot for target hardware
package-repositories:
  - type: apt
    components: [main, universe]
    architectures: [riscv64]
    suites: [noble, noble-security, noble-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

parts:
  u-boot:
    plugin: nil
    stage-packages:
      - u-boot-starfive:${CRAFT_ARCH_BUILD_FOR}
    organize:
      usr/lib/u-boot/starfive_visionfive2/u-boot.itb: visionfive2_fw_payload.img
      usr/lib/u-boot/starfive_visionfive2/u-boot-spl.bin.normal.out: u-boot-spl.bin.normal.out
    stage:
      - u-boot-spl.bin.normal.out
      - visionfive2_fw_payload.img

  grub:
    after: [u-boot]
    plugin: dump
    source: grub/
    stage-packages:
      - grub-efi-${CRAFT_ARCH_BUILD_FOR}:${CRAFT_ARCH_BUILD_FOR}
    override-build: |
      craftctl default

      craftctl set version=$(find "${CRAFT_PART_BUILD}/../stage_packages/" \
                              -name grub-efi-${CRAFT_ARCH_BUILD_FOR}_*.deb \
                              -exec dpkg-deb -f {} Version \;)

      # grub.conf is required when bootloader is set to GRUB in the gadget.yaml
      # so that snapd knows how to prepare the boot environment during image build
      # and during general run mode
      touch "${CRAFT_PART_INSTALL}/grub.conf"

      # Ubuntu does not ship either a grub binary nor a signed binary+shim on
      # this architecture As a result, we have to build the binary ourselves.
      # Here are at least the more useful grub modules required for Ubuntu Core:
      GRUB_MODULES="all_video boot cat chain configfile echo ext2 fat font  \
                    gettext gfxmenu gfxterm gfxterm_background gzio halt    \
                    jpeg keystatus loadenv loopback linux memdisk minicmd   \
                    normal part_gpt png reboot regexp search search_fs_uuid \
                    search_fs_file search_label sleep squash4 test true video"

      # grub.builtin is a GRUB cfg file that we embed in GRUB to automate
      # the booting process. It will search for a grub.cfg in the ubuntu-boot
      # partition and if it doesn't exist fallback to the one in the ubuntu-seed
      # partition. Both of these assets are controlled by snapd because we
      # select GRUB as our bootloader.

      "${CRAFT_PART_INSTALL}/usr/bin/grub-mkimage" -v -p efi                   \
        -O ${CRAFT_ARCH_BUILD_FOR}-efi -c "${CRAFT_PART_INSTALL}/grub.builtin" \
        -o "${CRAFT_PART_INSTALL}/grub${CRAFT_ARCH_BUILD_FOR}.efi"             \
        -d "${CRAFT_PART_INSTALL}/usr/lib/grub/${CRAFT_ARCH_BUILD_FOR}-efi"    \
        ${GRUB_MODULES}

      # uEnv.txt is a file that our u-boot binary will search for and source on
      # boot. This file should launch our grubriscv64.efi binary and results in
      # a fully automated boot process.
    organize:
      usr/share/doc/grub-efi-riscv64/:     licenses/grub-efi-riscv64/
      usr/share/doc/grub-efi-riscv64-bin/: licenses/grub-efi-riscv64-bin/
    stage:
      - grub.conf
      - grubriscv64.efi
      - licenses/
      - uEnv.txt

hooks:
  prepare-device:
    environment:
      MODEL_APIKEY: ""
