---
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 Isaac True

name: orange-pi-5plus-gadget
summary: A gadget for the Orange Pi 5+ for use with Ubuntu Core 22
description: |
  A gadget for the Orange Pi 5+ for use with Ubuntu Core 22
adopt-info: u-boot
base: core22
confinement: strict
type: gadget

architectures:
  - build-on:
      - arm64
      - amd64
    build-for: arm64

parts:
  rkbin:
    plugin: dump
    source: https://github.com/rockchip-linux/rkbin.git
    source-branch: master
    source-type: git
    organize:
      "*": rkbin/
    prime:
      - -*

  u-boot:
    after:
      - rkbin
    plugin: nil
    source: https://github.com/u-boot/u-boot.git
    source-tag: v2024.01-rc3
    source-type: git
    source-depth: 1
    build-packages:
      - make
      - ccache
      - device-tree-compiler
      - bison
      - flex
      - python3
      - python-is-python3
      - python3-setuptools
      - python3-pyelftools
      - python3-dev
      - swig
      - libssl-dev
      - on arm64:
          - gcc
      - else:
          - gcc-${CRAFT_ARCH_TRIPLET}
    build-environment:
      - ARCH: "arm"
      - CROSS_COMPILE: "${CRAFT_ARCH_TRIPLET}-"
      - PATH: "/usr/lib/ccache:${PATH}"
      - BL31: "${CRAFT_STAGE}/rkbin/bin/rk35/rk3588_bl31_v1.40.elf"
      - BL32: "${CRAFT_STAGE}/rkbin/bin/rk35/rk3588_bl32_v1.13.bin"
      - ROCKCHIP_TPL: "${CRAFT_STAGE}/rkbin/bin/rk35/rk3588_ddr_lp4_2112MHz_lp5_2736MHz_v1.12.bin"
    override-build: |
      make orangepi-5-plus-rk3588_defconfig
      echo CONFIG_BOOTDELAY=0 >> .config
      make
      cp u-boot-rockchip.bin ${CRAFT_PART_INSTALL}/

      VER=$(strings u-boot-rockchip.bin | grep -E '^U-Boot [0-9]+' | cut -f2 -d\ )

      craftctl set version="${VER}"
      craftctl set grade="devel"
    prime:
      - u-boot-rockchip.bin

  # File required by Ubuntu Core
  u-boot-conf:
    plugin: nil
    override-build: |
      touch ${CRAFT_PART_INSTALL}/uboot.conf

  # File required by Ubuntu Core
  boot-sel:
    plugin: nil
    build-packages:
      - u-boot-tools
    override-build: |
      mkenvimage -r -s 4096 -o ${CRAFT_PART_INSTALL}/boot.sel - < /dev/null

  boot-scr:
    plugin: nil
    source: u-boot
    override-build: |
      mkimage -A arm64 -T script -C none -n 'Boot Script' -d boot.scr.in \
        ${CRAFT_PART_INSTALL}/boot.scr
    build-packages:
      - u-boot-tools

  hooks:
    plugin: nil
    source: hooks
    stage-packages:
      - uuid-runtime:${CRAFT_TARGET_ARCH}
    override-build: |
      if [[ -z ${MODEL_APIURL+x} || -z ${MODEL_APIKEY+x} ]]; then
        echo "MODEL_APIKEY or MODEL_APIURL not set; not creating prepare-device hook"
      else
        sed -i "s;<<<MODEL_APIURL>>>;${MODEL_APIURL};" \
          ${CRAFT_PART_BUILD}/prepare-device.inc
        sed -i "s;<<<MODEL_APIKEY>>>;${MODEL_APIKEY};" \
          ${CRAFT_PART_BUILD}/prepare-device.inc

        install -Dm0755 ${CRAFT_PART_BUILD}/prepare-device.inc \
          ${CRAFT_PART_INSTALL}/snap/hooks/prepare-device
      fi
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/bash-completion

  fixups:
    plugin: nil
    source: fixups
    stage-packages:
      - ethtool:${CRAFT_TARGET_ARCH}
    override-build: |
      install -Dm0755 ${CRAFT_PART_BUILD}/disable-offload.sh \
        -t ${CRAFT_PART_INSTALL}/usr/local/bin

apps:
  disable-offload:
    command: usr/local/bin/disable-offload.sh
    daemon: oneshot
    plugs:
      - network-control
