name: Snap Builds CI

# This workflow is intended to test that each snap provided as an example can be
# built with some relevant version of snapcraft, with the aim of hopefully
# catching bugs or regressions.
# Please only create AMD64 build-on jobs. If you want non-AMD64 builds, use Launchpad.

# Run the jobs on:
#   1) 12PM UTC weekly on Monday
on:
  schedule:
    - cron: '0 12 * * MON'
  workflow_dispatch:

# Convention:
# jobs:
#   build_<branch name>_<snapcraft track>:
#     name: <snapcraft track> job for <branch> snap
#     runs-on: ubuntu-<base>
#     steps:
#       - name: Checkout <branch>
#         uses: actions/checkout@v4
#         with:
#           ref: <branch>
#       - name: Test build of <branch> snap with snapcraft <channel>
#         uses: snapcore/action-build@v1
#         with:
#           snapcraft-channel: <track>/<risk>/<branch>
#           snapcraft-args: --verbosity=verbose

jobs:
  build_22_amd64_pc_7:
    name: 7.x/edge job for 22-amd64-pc snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-amd64-pc
        uses: actions/checkout@v4
        with:
          ref: 22-amd64-pc
      - name: Test build of 22-amd64-pc with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_amd64_pc_latest:
    name: latest/edge job for 22-amd64-pc snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-amd64-pc
        uses: actions/checkout@v4
        with:
          ref: 22-amd64-pc
      - name: Test build of 22-amd64-pc with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_amd64_pc_classic_7:
    name: 7.x/edge job for 22-amd64-pc-classic snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-amd64-pc-classic
        uses: actions/checkout@v4
        with:
          ref: 22-amd64-pc-classic
      - name: Test build of 22-amd64-pc-classic with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_amd64_pc_classic_latest:
    name: latest/edge job for 22-amd64-pc-classic snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-amd64-pc-classic
        uses: actions/checkout@v4
        with:
          ref: 22-amd64-pc-classic
      - name: Test build of 22-amd64-pc-classic with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_arm64_odroid_hc4_7:
    name: 7.x/edge job for 22-arm64-odroid-hc4 snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-arm64-odroid-hc4
        uses: actions/checkout@v4
        with:
          ref: 22-arm64-odroid-hc4
      - name: Test build of 22-arm64-odroid-hc4 with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_arm64_odroid_hc4_latest:
    name: latest/edge job for 22-arm64-odroid-hc4 snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-arm64-odroid-hc4
        uses: actions/checkout@v4
        with:
          ref: 22-arm64-odroid-hc4
      - name: Test build of 22-arm64-odroid-hc4 with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_arm64_orange_pi_5plus_7:
    name: 7.x/edge job for 22-arm64-orange-pi-5plus snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-arm64-orange-pi-5plus
        uses: actions/checkout@v4
        with:
          ref: 22-arm64-orange-pi-5plus
      - name: Fix variable names
        run: |
          sed -i 's/CRAFT_ARCH_BUILD_FOR/CRAFT_TARGET_ARCH/' snap/snapcraft.yaml
          sed -i 's/CRAFT_ARCH_TRIPLET_BUILD_FOR/CRAFT_ARCH_TRIPLET/' snap/snapcraft.yaml
      - name: Test build of 22-arm64-orange-pi-5plus with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_arm64_orange_pi_5plus_latest:
    name: latest/edge job for 22-arm64-orange-pi-5plus snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-arm64-orange-pi-5plus
        uses: actions/checkout@v4
        with:
          ref: 22-arm64-orange-pi-5plus
      - name: Test build of 22-arm64-orange-pi-5plus with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_riscv64_icicle_7:
    name: 7.x/edge job for 22-riscv64-icicle snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-icicle
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-icicle
      - name: Test build of 22-riscv64-icicle with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_riscv64_icicle_latest:
    name: latest/edge job for 22-riscv64-icicle snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-icicle
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-icicle
      - name: Test build of 22-riscv64-icicle with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_riscv64_nezha_7:
    name: 7.x/edge job for 22-riscv64-nezha snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-nezha
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-nezha
      - name: Test build of 22-riscv64-nezha with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_riscv64_nezha_latest:
    name: latest/edge job for 22-riscv64-nezha snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-nezha
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-nezha
      - name: Test build of 22-riscv64-nezha with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose

  build_22_riscv64_virt_7:
    name: 7.x/edge job for 22-riscv64-virt snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-virt
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-virt
      - name: Test build of 22-riscv64-virt with snapcraft 7.x/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 7.x/edge
          snapcraft-args: --verbosity=verbose
  build_22_riscv64_virt_latest:
    name: latest/edge job for 22-riscv64-virt snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 22-riscv64-virt
        uses: actions/checkout@v4
        with:
          ref: 22-riscv64-virt
      - name: Test build of 22-riscv64-virt with snapcraft latest/edge
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
          snapcraft-args: --verbosity=verbose
