name: Snap Builds CI

# This workflow is intended to test that each gadget snap can be built with some
# relevant version of snapcraft, with the aim of hopefully catching bugs or
# regressions.

# Run the jobs on:
#   1) 12PM UTC weekly on Monday
# Note that scheduled workflows must reside on the default branch. We can then
# checkout each relevant branch to run the job on in our Checkout step.
on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

# The following jobs are the actual jobs to be run
# Convention:
#   build_{directory}:
#     name: Build job for {directory} snap
#     runs-on: ubuntu-{target}
#     outputs:
#       snap-file: ${{ steps.build-snap.outputs.snap }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Test build of {directory} snap
#         uses: snapcore/action-build@v1
#         with:
#           path: {directory}/
#           build-info: true
#           snapcraft-channel: {track}/{risk}/{branch}
#         id: build-snap
jobs:
  build_22_riscv64_icicle:
    name: Build job for 22-riscv64-icicle gadget snap
    runs-on: ubuntu-22.04
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 22-riscv64-icicle
      - name: Test build of 22-riscv64-icicle gadget snap
        uses: snapcore/action-build@v1
        with:
          build-info: true
          snapcraft-channel: latest/edge
        id: build-snap

  build_22_riscv64_virt:
    name: Build job for 22-riscv64-virt gadget snap
    runs-on: ubuntu-22.04
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 22-riscv64-virt
      - name: Test build of 22-riscv64-virt gadget snap
        uses: snapcore/action-build@v1
        with:
          build-info: true
          snapcraft-channel: latest/edge
        id: build-snap

  build_22.04_amd64_pc:
    name: Build job for the Classic gadget snap
    runs-on: ubuntu-22.04
    outputs:
      snap-file: ${{ steps.build.outputs.snap }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 22.04-amd64-pc
      - name: Prep env
        run: |
          sed -i "s/APIKEY_STANDIN/${{ secrets.CLASSIC_MODEL_APIKEY }}/"      snap/snapcraft.yaml
          sed -i "s/name: pc/name: ${{ secrets.REGISTERED_NAME}}/"            snap/snapcraft.yaml
          sed -i "s/-partners.canonical.com/${{ secrets.SERIAL_VAULT_URL }}/" snap/hooks/prepare-device
      - name: Build
        uses: snapcore/action-build@v1
        with:
          build-info: true
          snapcraft-channel: 7.x/stable
          ua-token: ${{ secrets.UA_TOKEN }}
        id: build
      - name: Publish
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.IOTFIELD_STORE_CREDS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: classic/edge
